DPSapp/Controllers/UploadFilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace DPSapp.Controllers
{
    public class UploadFilesController : Controller
    {
        // GET: UploadFiles
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            try
            {
                if(file.ContentLength>0)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string filepath = Path.Combine(Server.MapPath("~/FilesUpload"),filename);
                    file.SaveAs(filepath);
                }
                ViewBag.Message = "Plik poprawnie załadowany!";
                return View();
            }
            catch (Exception)
            {
                ViewBag.Message = "Plik nie załadował się!";
                return View();
            }
            
        }
    }
}

DPSapp/Views/UploadFiles/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center>
    <h2>Upload Files</h2>
     @using (Html.BeginForm("Index", "UploadFiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div>
                    @Html.TextBox("file","",new { type="file"})
                    <input type="submit" value="Zapisz plik"/>
                    @ViewBag.Message
                </div>
            }
</center>